version: "3.9"
services:

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["pytest", "--cov", "cli", "--cov-report", "term-missing", "-v", "--pdb"]
    volumes:
      - ./cli:/app/cli
      - ./tests:/app/tests

  noop:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    command: ["python", "-m", "cli.cli", "--pd", "$PAGERDUTY", "--lirtoken", "$LIR_TOKEN", "--apiurl", "$LIR_URL", "--noop"]
    volumes:
      - ./cli:/app/cli

  migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    command: ["python", "-m", "cli.cli", "--pd", "$PAGERDUTY", "--lirtoken", "$LIR_TOKEN", "--apiurl", "$LIR_URL"]
    volumes:
      - ./cli:/app/cli
